# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Remedy research project
site_author: Patrick N. Raanes
site_url: https://remedy.no/
docs_dir: docs

repo_name: patnr/remedy.no
repo_url: https://github.com/patnr/remedy.no
copyright: Copyright &copy; 2023 NORCE

theme:
  name: material
  custom_dir: overrides

  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - header.autohide
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy

  palette:
    # Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple # deep orange
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to Dark Mode

    # Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to Light Mode

# Mostly from
# https://squidfunk.github.io/mkdocs-material/setup/extensions/#recommended-configuration
markdown_extensions:
  # Python Markdown official extensions
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Extensions part of Pymdown
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - glightbox
  - search
  # - roamlinks
  # - blog

hooks:
  - list_logos.py

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
  # For MathJax
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  generator: false
  # social:
  #   - icon: fontawesome/brands/mastodon
  #     link: https://fosstodon.org/@squidfunk
  #   - icon: fontawesome/brands/youtube
  #     link: https://youtube.com/neovim

  footer:
    logos:
      row1:
        - name: norce.svg
          height: 50px
          brightness: 50%
        - name: nfr.svg
          height: 80px
          brightness: 50%
      row2:
        - name: akerbp.svg
          height: 40px
          brightness: 50%
        - name: equinor.svg
          height: 60px
          brightness: 50%
        - name: wintershall-dea.svg
          height: 80px
          brightness: 70%
