[tool.poetry]
name = "remedy"
version = "0.1.0"
description = ""
authors = ["Patrick"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
mkdocs-material = "^9.5.2"
mkdocs-glightbox = "^0.3.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
